[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*

addopts = -v --tb=short

markers =
    wp: WordPress suite tests
    yandex: Yandex suite tests
    positive: Positive tests
    negative: Negative tests
    posts: Posts table tests
    d1: D1 test-cases
    d2: D2 test-cases
    d3: D3 test-cases
    d4: D4 test-cases
