[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*

addopts = -v --tb=short

markers =
    wp: WordPress suite tests
    positive: Positive tests
    negative: Negative tests
    posts: Posts table tests
